#!/usr/bin/env python3
"""
Production Configuration Script
Run this script to set up production environment variables
"""

import os
import secrets
import sys

def generate_secret_key():
    """Generate a secure secret key for production"""
    return secrets.token_urlsafe(32)

def setup_production_env():
    """Set up production environment variables"""
    
    print("🔧 Setting up Production Configuration...")
    
    # Generate secure secret key
    secret_key = generate_secret_key()
    
    # Production environment variables
    env_vars = {
        "SECRET_KEY": secret_key,
        "ACCESS_TOKEN_EXPIRE_MINUTES": "30",
        "REFRESH_TOKEN_EXPIRE_DAYS": "7",
        "DATABASE_URL": "postgresql://user:password@host:port/dbname?sslmode=require",
        "MAIL_USERNAME": "your-email@domain.com",
        "MAIL_PASSWORD": "your-email-password",
        "MAIL_FROM": "noreply@yourdomain.com",
        "MAIL_SERVER": "smtp.gmail.com",
        "MAIL_PORT": "587",
        "GOOGLE_CLIENT_ID": "your-google-client-id",
        "GOOGLE_CLIENT_SECRET": "your-google-client-secret",
        "APPLE_CLIENT_ID": "your-apple-client-id",
        "APPLE_TEAM_ID": "your-apple-team-id",
        "APPLE_KEY_ID": "your-apple-key-id",
        "APPLE_PRIVATE_KEY": "your-apple-private-key",
    }
    
    # Create .env.production file
    with open('.env.production', 'w') as f:
        f.write("# Production Environment Variables\n")
        f.write("# Generated by production_config.py\n\n")
        
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print("✅ Production environment file created: .env.production")
    print("\n📝 IMPORTANT: Update the following values in .env.production:")
    print("   - DATABASE_URL: Your production database connection string")
    print("   - MAIL_USERNAME/MAIL_PASSWORD: Your email service credentials")
    print("   - GOOGLE_CLIENT_ID/SECRET: Your Google OAuth credentials")
    print("   - APPLE_*: Your Apple OAuth credentials")
    
    return env_vars

def check_production_requirements():
    """Check if all production requirements are met"""
    
    print("\n🔍 Checking Production Requirements...")
    
    requirements = [
        "SECRET_KEY",
        "DATABASE_URL",
        "MAIL_USERNAME",
        "MAIL_PASSWORD",
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET"
    ]
    
    missing = []
    
    for req in requirements:
        if not os.getenv(req):
            missing.append(req)
    
    if missing:
        print(f"❌ Missing required environment variables: {', '.join(missing)}")
        return False
    else:
        print("✅ All required environment variables are set")
        return True

def main():
    """Main function"""
    
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        check_production_requirements()
    else:
        setup_production_env()

if __name__ == "__main__":
    main() 